In [12]:
#!pip install nltk

In [9]:
import nltk

In [10]:
#nltk.download() #select all-copora - Large Collection of Text

In [11]:
from nltk.corpus import brown

In [12]:
print(brown.categories())
print(len(brown.categories()))

['adventure', 'belles_lettres', 'editorial', 'fiction', 'government', 'hobbies', 'humor', 'learned', 'lore', 'mystery', 'news', 'religion', 'reviews', 'romance', 'science_fiction']
15


In [13]:
data=brown.sents(categories='adventure')
data

[['Dan', 'Morgan', 'told', 'himself', 'he', 'would', 'forget', 'Ann', 'Turner', '.'], ['He', 'was', 'well', 'rid', 'of', 'her', '.'], ...]

In [14]:
len(data) #no of sentences

4637

In [15]:
# 1 sentence
' '.join(data[0])

'Dan Morgan told himself he would forget Ann Turner .'

# Bag of Words Pipeline - Convert Text to Numeric

Here it is called bag because the order of the words dont matter

- Get the data/corpus

- Tokenisation , Stopward Removal:
  Tokensization referes to breaking up the documents to sentences then to finally words
  Stopward Removal: Removing unuseful words like I,the,a,an,you etc.,.
  
- Stemming: Convert different words having same meaning to a common word. Like runs, running, ran => run

- Building a Vocab

- Vectorization
- Classification

## Tokenisation , Stopward Removal

In [16]:
#nltk.download('punkt')

In [17]:
document="""It was a very pleasant day. The weather was cool and there were light showers. I went to the market to buy 
            some fruits."""

sentence='Send all the 50 documents related to chapters 1,2,3 at manjari.jain@bofa.com'

In [18]:
from nltk.tokenize import sent_tokenize,word_tokenize

In [19]:
sents=sent_tokenize(document)
print(sents)
print(len(sents))
print(sents[0])

['It was a very pleasant day.', 'The weather was cool and there were light showers.', 'I went to the market to buy \n            some fruits.']
3
It was a very pleasant day.


In [20]:
words_1=sentence.split()
words_1

['Send',
 'all',
 'the',
 '50',
 'documents',
 'related',
 'to',
 'chapters',
 '1,2,3',
 'at',
 'manjari.jain@bofa.com']

In [21]:
words_2=word_tokenize(sentence)
words_2

['Send',
 'all',
 'the',
 '50',
 'documents',
 'related',
 'to',
 'chapters',
 '1,2,3',
 'at',
 'manjari.jain',
 '@',
 'bofa.com']

### Tokenisation using Regex

In [22]:
sentence='Send all the 50 documents related to chapters 1,2,3 at manjari.jain@bofa.com'

In [23]:
from nltk.tokenize import RegexpTokenizer

In [24]:
tokenizer=RegexpTokenizer('[a-zA-Z]+')
useful_words=tokenizer.tokenize(sentence)
print(useful_words)

['Send', 'all', 'the', 'documents', 'related', 'to', 'chapters', 'at', 'manjari', 'jain', 'bofa', 'com']


In [25]:
tokenizer=RegexpTokenizer('[a-zA-Z@]+')
useful_words=tokenizer.tokenize(sentence)
print(useful_words)

['Send', 'all', 'the', 'documents', 'related', 'to', 'chapters', 'at', 'manjari', 'jain@bofa', 'com']


In [26]:
tokenizer=RegexpTokenizer('[a-zA-Z.]+')
useful_words=tokenizer.tokenize(sentence)
print(useful_words)

['Send', 'all', 'the', 'documents', 'related', 'to', 'chapters', 'at', 'manjari.jain', 'bofa.com']


In [27]:
tokenizer=RegexpTokenizer('[a-zA-Z@.]+')
useful_words=tokenizer.tokenize(sentence)
print(useful_words)

['Send', 'all', 'the', 'documents', 'related', 'to', 'chapters', 'at', 'manjari.jain@bofa.com']


### Stopward Removal

In [28]:
from nltk.corpus import stopwords

In [29]:
sw=set(stopwords.words('english'))
print(sw)

{'she', 'does', 'shouldn', 'd', 'over', 'some', "aren't", 'her', 'while', 'so', 'o', 'won', 'my', 'your', 'it', 'on', 'where', 'we', 'for', 'doesn', "wouldn't", 'above', 'by', 'hasn', 'them', 'ain', "mightn't", 'haven', 'very', 'yours', 'any', 'do', 'but', "you'd", 'under', 'now', 'y', 'ourselves', 'itself', 'themselves', 'most', 'theirs', 'of', 'was', 'yourself', 'in', 'to', 'ours', 'when', 'few', 'him', "you've", 'did', "couldn't", 'from', 'here', 'hadn', "mustn't", 'needn', 'i', "you're", "you'll", 'both', 'no', 'just', 'only', 'don', "weren't", "won't", 'whom', "she's", 'have', 'our', 'weren', 'herself', 'again', 'against', 'once', 'if', 'can', 'they', 'mightn', 'the', 'will', 'than', "needn't", 'aren', 'couldn', 'its', "don't", 'he', "shan't", 'such', 'other', "that'll", 'nor', 'am', 'be', 'each', 't', "doesn't", 'and', 'mustn', 'these', 'after', 'should', 'myself', 'or', 'until', 'as', "didn't", 'you', 'a', 'before', 'out', 'up', 'who', 'his', 'doing', 'through', 'this', 'that', 

In [30]:
def remove_stopwords(sentence,sw):
    useful_words=[w for w in sentence if w not in sw]
    return useful_words

In [31]:
text="Hi, My name is Manjari Jain. I am an Iron Man. I am not a superman".split()

print(text)

['Hi,', 'My', 'name', 'is', 'Manjari', 'Jain.', 'I', 'am', 'an', 'Iron', 'Man.', 'I', 'am', 'not', 'a', 'superman']


In [32]:
print(remove_stopwords(text,sw))

# here it removes "not" word also. Meaning it can effect our negation

['Hi,', 'My', 'name', 'Manjari', 'Jain.', 'I', 'Iron', 'Man.', 'I', 'superman']


In [33]:
def remove_stopwords(sentence,sw):
    useful_words=[w for w in sentence if w=="not" or w not in sw]
    return useful_words

In [34]:
print(remove_stopwords(text,sw))

['Hi,', 'My', 'name', 'Manjari', 'Jain.', 'I', 'Iron', 'Man.', 'I', 'not', 'superman']


### Stemming

- Process that transforms particular words (verbs,plurals) into radical form
- Preserves the semantics of the sentences without increasing the no of tokens
- Example: jumps, jumping, jumped, jump => jump

In [35]:
text="""Fox love to make jumps. The quick brown fox was seen jumping over the lovely dog from a 6ft high wall."""

In [36]:
'''There are three types of Stemmers provided by the nltk- Snowball, Porter, Lancas Stemmer'''

from nltk.stem.snowball import SnowballStemmer, PorterStemmer
from nltk.stem.lancaster import LancasterStemmer

In [37]:
#Porter Stemmer
ps=PorterStemmer()

ps.stem('jumping'),ps.stem('jumped'),ps.stem('jumps'),ps.stem('jump')

('jump', 'jump', 'jump', 'jump')

In [38]:
ps.stem('lovely'),ps.stem('loving')

('love', 'love')

In [39]:
#Snowball Stemmer

ss=SnowballStemmer('english')
ss.stem('jumping'),ss.stem('jumped'),ss.stem('jumps'),ss.stem('jump'),ss.stem('jumpful')

('jump', 'jump', 'jump', 'jump', 'jump')

In [40]:
ss.stem('lovely'),ss.stem('loving')

('love', 'love')

### Lementization

In [41]:
from nltk.stem import WordNetLemmatizer

In [42]:
wl=WordNetLemmatizer()

wl.lemmatize('jumped')

'jumped'

### Testing so far learnt

In [43]:
corpus=[
    'India Cricket Team will win world cup says capt. Virat Kohli. World Cup will be held at Sri Lanka',
    'We will win next Lok Sabha Elections, says confident Indian PM',
    'The nobel laurate won the hearts of the people',
    'The movie Razi is an exciting Indian Spy Thriller based up on a real story',
    'Fox love to make jumps.', 
    'The quick brown fox was seen jumping over the lovely dog from a 6ft high wall.'
]

In [44]:
corpus[0]

'India Cricket Team will win world cup says capt. Virat Kohli. World Cup will be held at Sri Lanka'

In [45]:
#Tokenization

from nltk.tokenize import RegexpTokenizer

def tokenization(text):
    tokenizer=RegexpTokenizer('[a-zA-Z]+')
    return tokenizer.tokenize(text)

def final_token(sent_list):
    words=[]
    for sent in sent_list:
        new_words=tokenization(sent)
        new_words=[w.lower() for w in new_words]
        words.extend(new_words)
        
    return words

In [46]:
words=final_token(corpus)
print(words,len(words))

['india', 'cricket', 'team', 'will', 'win', 'world', 'cup', 'says', 'capt', 'virat', 'kohli', 'world', 'cup', 'will', 'be', 'held', 'at', 'sri', 'lanka', 'we', 'will', 'win', 'next', 'lok', 'sabha', 'elections', 'says', 'confident', 'indian', 'pm', 'the', 'nobel', 'laurate', 'won', 'the', 'hearts', 'of', 'the', 'people', 'the', 'movie', 'razi', 'is', 'an', 'exciting', 'indian', 'spy', 'thriller', 'based', 'up', 'on', 'a', 'real', 'story', 'fox', 'love', 'to', 'make', 'jumps', 'the', 'quick', 'brown', 'fox', 'was', 'seen', 'jumping', 'over', 'the', 'lovely', 'dog', 'from', 'a', 'ft', 'high', 'wall'] 75


In [47]:
#Stopwards Removal

from nltk.corpus import stopwords

sw=set(stopwords.words('english'))

def remove_stopwords(words,sw):
    useful_words=[w for w in words if w=="not" or w not in sw]
    return useful_words

In [48]:
new_words=remove_stopwords(words,sw)
print(new_words,len(new_words))

['india', 'cricket', 'team', 'win', 'world', 'cup', 'says', 'capt', 'virat', 'kohli', 'world', 'cup', 'held', 'sri', 'lanka', 'win', 'next', 'lok', 'sabha', 'elections', 'says', 'confident', 'indian', 'pm', 'nobel', 'laurate', 'hearts', 'people', 'movie', 'razi', 'exciting', 'indian', 'spy', 'thriller', 'based', 'real', 'story', 'fox', 'love', 'make', 'jumps', 'quick', 'brown', 'fox', 'seen', 'jumping', 'lovely', 'dog', 'ft', 'high', 'wall'] 51


In [49]:
# Stemming

from nltk.stem.snowball import PorterStemmer

ps=PorterStemmer()

def stemming(words):
    res=[]
    for w in words:
        if ps.stem(w) not in res:
            res.append(ps.stem(w))
        
    return res

In [50]:
stem_words=stemming(new_words)
print(stem_words,len(stem_words))

['india', 'cricket', 'team', 'win', 'world', 'cup', 'say', 'capt', 'virat', 'kohli', 'held', 'sri', 'lanka', 'next', 'lok', 'sabha', 'elect', 'confid', 'indian', 'pm', 'nobel', 'laurat', 'heart', 'peopl', 'movi', 'razi', 'excit', 'spi', 'thriller', 'base', 'real', 'stori', 'fox', 'love', 'make', 'jump', 'quick', 'brown', 'seen', 'dog', 'ft', 'high', 'wall'] 43


### Building a Vocab

In [51]:
corpus=[
    'India Cricket Team will win world cup says capt. Virat Kohli. World Cup will be held at Sri Lanka',
    'We will win next Lok Sabha Elections, says confident Indian PM',
    'The nobel laurate won the hearts of the people',
    'The movie Razi is an exciting Indian Spy Thriller based up on a real story'
]

corpus[0]

'India Cricket Team will win world cup says capt. Virat Kohli. World Cup will be held at Sri Lanka'

In [52]:
from sklearn.feature_extraction.text import CountVectorizer

In [53]:
cv=CountVectorizer()
vectorized_corpus=cv.fit_transform(corpus)
vectorized_corpus

<4x43 sparse matrix of type '<class 'numpy.int64'>'
	with 48 stored elements in Compressed Sparse Row format>

In [54]:
vectorized_corpus?

In [55]:
vectorized_corpus=vectorized_corpus.toarray()
vectorized_corpus

array([[0, 1, 0, 1, 1, 0, 1, 2, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 2, 1, 0, 2],
       [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
        1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [56]:
len(vectorized_corpus)

4

In [57]:
vectorized_corpus[0] #first sentence

array([0, 1, 0, 1, 1, 0, 1, 2, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 2, 1, 0, 2],
      dtype=int64)

In [58]:
len(vectorized_corpus[0])

43

In [59]:
''' It is first finding the length of unique words in all sentences of corpus
    It found out there are 43 unique words overall
    Then it creates four separate rows: one representing each sentence of length 43
    It starts with first sentence
(a) Then it counts the no of times 0th Index ("an") to 42th Index ("world") is coming in the sentence. 
    Then it moves for second sentence and repeats "a" step
'''

print(cv.vocabulary_)#word=> wrt the indexes
print(len(cv.vocabulary_.keys()))

{'india': 12, 'cricket': 6, 'team': 33, 'will': 39, 'win': 40, 'world': 42, 'cup': 7, 'says': 29, 'capt': 4, 'virat': 37, 'kohli': 15, 'be': 3, 'held': 11, 'at': 1, 'sri': 31, 'lanka': 16, 'we': 38, 'next': 20, 'lok': 18, 'sabha': 28, 'elections': 8, 'confident': 5, 'indian': 13, 'pm': 25, 'the': 34, 'nobel': 21, 'laurate': 17, 'won': 41, 'hearts': 10, 'of': 22, 'people': 24, 'movie': 19, 'razi': 26, 'is': 14, 'an': 0, 'exciting': 9, 'spy': 30, 'thriller': 35, 'based': 2, 'up': 36, 'on': 23, 'real': 27, 'story': 32}
43


In [60]:
# Inverse Mapping

numbers=vectorized_corpus[2]
numbers

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 1, 0],
      dtype=int64)

In [61]:
sent=cv.inverse_transform(numbers) # we are getting unique words from the sentence at 2nd Index
sent

[array(['hearts', 'laurate', 'nobel', 'of', 'people', 'the', 'won'],
       dtype='<U9')]

### Vectorization with Stopwords and Stemming

In [62]:
from nltk.stem.snowball import PorterStemmer

ps=PorterStemmer()

def stemming(words):
    res=[]
    for w in words:
        if ps.stem(w) not in res:
            res.append(ps.stem(w))
        
    return res

In [63]:
def remove_stopwords(words,sw):
    useful_words=[w for w in words if w=="not" or w not in sw]
    return useful_words

In [64]:
from nltk.tokenize import RegexpTokenizer
tokenizer=RegexpTokenizer('[a-zA-Z.@]+')

def mytokenizer(text):
    words=tokenizer.tokenize(text)
    words=remove_stopwords(words,sw)
    return stemming(words)

In [65]:
mytokenizer(sentence),sentence

(['send', 'document', 'relat', 'chapter', 'manjari.jain@bofa.com'],
 'Send all the 50 documents related to chapters 1,2,3 at manjari.jain@bofa.com')

In [66]:
cv=CountVectorizer(tokenizer=mytokenizer)
vectorized_corpus=cv.fit_transform(corpus).toarray()

In [67]:
vectorized_corpus

array([[0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 0, 1, 0, 1, 1, 1],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
        0, 0, 1, 0, 1, 0, 1, 0, 0, 0]], dtype=int64)

In [68]:
len(vectorized_corpus[0])

32

In [69]:
# Inverse Mapping

numbers=vectorized_corpus[0]
sent=cv.inverse_transform(numbers) # we are getting unique words from the sentence at 2nd Index
sent

[array(['capt.', 'cricket', 'cup', 'held', 'india', 'kohli.', 'lanka',
        'say', 'sri', 'team', 'virat', 'win', 'world'], dtype='<U8')]

In [70]:
#test data

test_data=[
    'Razi is jumping on the hill'
]

cv.transform(test_data).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [71]:
print(cv.vocabulary_)

{'india': 9, 'cricket': 3, 'team': 27, 'win': 30, 'world': 31, 'cup': 4, 'say': 23, 'capt.': 1, 'virat': 29, 'kohli.': 11, 'held': 8, 'sri': 25, 'lanka': 12, 'next': 16, 'lok': 14, 'sabha': 22, 'elect': 5, 'confid': 2, 'indian': 10, 'pm': 19, 'nobel': 17, 'laurat': 13, 'heart': 7, 'peopl': 18, 'movi': 15, 'razi': 20, 'excit': 6, 'spi': 24, 'thriller': 28, 'base': 0, 'real': 21, 'stori': 26}


### More ways to create features

- Unigrams - Treat every word as the feature
- Bigrams - 
- Trigrams
- n-grams
- TF-IDF Normalisation

In [98]:
sent_1=['This is a good movie']
sent_2=['This is not a good movie']

In [99]:
doc=[sent_1[0],sent_2[0]]
doc

['This is a good movie', 'This is not a good movie']

In [100]:
cv=CountVectorizer()

In [101]:
vc=cv.fit_transform(doc).toarray()
vc

array([[1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [102]:
cv.vocabulary_

{'this': 4, 'is': 1, 'good': 0, 'movie': 2, 'not': 3}

In [106]:
#Bi Gram 

cv_bigram=CountVectorizer(ngram_range=(2,2))

cv_bigram.fit_transform(doc)
cv_bigram.vocabulary_

{'this is': 4, 'is good': 1, 'good movie': 0, 'is not': 2, 'not good': 3}

In [105]:
# Tri Gram

cv_trigram=CountVectorizer(ngram_range=(3,3))
cv_trigram.fit_transform(doc)
cv_trigram.vocabulary_

{'this is good': 3,
 'is good movie': 0,
 'this is not': 4,
 'is not good': 1,
 'not good movie': 2}

In [111]:
# N Gram

cv_ngram=CountVectorizer(ngram_range=(1,3))
cv_ngram.fit_transform(doc)
cv_ngram.vocabulary_

{'this': 11,
 'is': 2,
 'good': 0,
 'movie': 7,
 'this is': 12,
 'is good': 3,
 'good movie': 1,
 'this is good': 13,
 'is good movie': 4,
 'not': 8,
 'is not': 5,
 'not good': 9,
 'this is not': 14,
 'is not good': 6,
 'not good movie': 10}

### TF-IDF Normalisation (Term Frequency - Inverse Document Frequency)

- Avoid features that occurs very often as they contain less info
- Info decreases as the no of occurence increases across different types of documents
- So, we define another term : term-document-frequency which associates a weight with every term

In [122]:
sent_1="this is good movie"
sent_2="this was good movie"
sent_3="this is not good movie"

corpus=[sent_1,sent_2,sent_3]

In [123]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [124]:
tfidf=TfidfVectorizer()

In [125]:
vc=tfidf.fit_transform(corpus).toarray()
vc

array([[0.46333427, 0.59662724, 0.46333427, 0.        , 0.46333427,
        0.        ],
       [0.41285857, 0.        , 0.41285857, 0.        , 0.41285857,
        0.69903033],
       [0.3645444 , 0.46941728, 0.3645444 , 0.61722732, 0.3645444 ,
        0.        ]])

In [126]:
tfidf.vocabulary_

{'this': 4, 'is': 1, 'good': 0, 'movie': 2, 'was': 5, 'not': 3}