In [185]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

plt.style.use("seaborn")

In [186]:
dfx=pd.read_csv("Train.csv")
dfx

feature_1  feature_2  feature_3  feature_4  feature_5      target
0      0.293416  -0.945599  -0.421105   0.406816   0.525662  -82.154667
1     -0.836084  -0.189228  -0.776403  -1.053831   0.597997  -48.897960
2      0.236425   0.132836  -0.147723   0.699854  -0.187364   77.270371
3      0.175312   0.143194  -0.581111  -0.122107  -1.292168   -2.988581
4     -1.693011   0.542712  -2.798729  -0.686723   1.244077  -37.596722
...         ...        ...        ...        ...        ...         ...
1595  -0.274961  -0.820634  -0.757173  -0.147555  -0.307149  -80.110012
1596  -0.076099   0.255257   0.290054   1.796036   0.340350  118.315601
1597   1.044177  -0.899206   1.730399  -1.871057   0.442520 -107.510508
1598  -1.269173  -0.005052   1.857669  -1.080365   0.736334  -47.341558
1599  -1.884000  -0.849427  -1.452270   0.488613   1.459576 -115.939003

[1600 rows x 6 columns]

In [187]:
dfx.describe()

feature_1    feature_2    feature_3    feature_4    feature_5  \
count  1600.000000  1600.000000  1600.000000  1600.000000  1600.000000   
mean      0.004114    -0.027604    -0.044459    -0.042408     0.012005   
std       0.997338     1.021776     1.011768     1.017189     0.978654   
min      -3.380125    -3.314844    -3.153118    -3.250169    -2.851707   
25%      -0.647165    -0.705030    -0.706385    -0.709504    -0.615880   
50%      -0.000360    -0.043769    -0.041272    -0.029756    -0.013527   
75%       0.682118     0.645442     0.639130     0.646290     0.650089   
max       3.287205     3.438895     3.216176     2.985410     3.321770   

            target  
count  1600.000000  
mean      0.318835  
std     110.741562  
min    -379.829794  
25%     -71.897040  
50%      -0.610665  
75%      71.226603  
max     337.643014

In [188]:
data=dfx.values
X=data[:,:-1]
Y=data[:,-1]

#Y=Y.reshape(-1,1)

X.shape,Y.shape

((1600, 5), (1600,))

In [189]:
X

array([[ 0.29341624, -0.94559871, -0.42110515,  0.40681602,  0.52566183],
       [-0.83608408, -0.18922804, -0.77640262, -1.05383124,  0.59799685],
       [ 0.23642511,  0.13283602, -0.14772298,  0.69985396, -0.18736416],
       ...,
       [ 1.04417694, -0.89920649,  1.73039905, -1.87105676,  0.44251965],
       [-1.2691729 , -0.00505216,  1.85766873, -1.08036482,  0.73633394],
       [-1.88400025, -0.84942743, -1.45227035,  0.48861308,  1.4595758 ]])

# Normalise

In [190]:
X_mean=np.mean(X,axis=0)
X_mean

array([ 0.0041143 , -0.0276038 , -0.04445943, -0.04240792,  0.01200535])

In [191]:
X_std=np.std(X,axis=0)
X_std

array([0.99702582, 1.02145636, 1.01145129, 1.01687155, 0.97834768])

In [192]:
X_new=(X-X_mean)/X_std
X_new

array([[ 0.29016495, -0.89871183, -0.37238147,  0.44177059,  0.52502448],
       [-0.84270473, -0.15822922, -0.72365639, -0.99464217,  0.59896038],
       [ 0.23300381,  0.15706968, -0.10209444,  0.72994655, -0.20378187],
       ...,
       [ 1.0431652 , -0.8532941 ,  1.75476416, -1.79830858,  0.44004223],
       [-1.27708547,  0.02207793,  1.88059294, -1.0207355 ,  0.74035908],
       [-1.89374689, -0.80456069, -1.39187219,  0.52221049,  1.47960738]])

# Split

In [193]:
from sklearn import model_selection


X_train,X_test,Y_train,Y_test=model_selection.train_test_split(X_new,Y,random_state=1)

X_train.shape,Y_train.shape,X_test.shape,Y_test.shape

((1200, 5), (1200,), (400, 5), (400,))

In [194]:
ones=np.ones((X_train.shape[0],1))
X_train=np.hstack((ones,X_train))
X_train

array([[ 1.        ,  0.25330287, -0.14377261, -1.66638985,  0.43623911,
         0.26449893],
       [ 1.        ,  0.31834477,  0.14336819,  0.01197155, -1.06106652,
         1.95254004],
       [ 1.        ,  1.41096708, -0.34560928, -1.8169995 ,  1.04375735,
        -0.08790039],
       ...,
       [ 1.        , -0.35327315,  0.46626121, -2.57736097,  0.16216951,
         0.40018002],
       [ 1.        ,  0.5660426 ,  1.4247213 , -1.01918926, -0.24146755,
         0.24531577],
       [ 1.        ,  0.23897045, -0.03128457,  1.19799609,  0.07427737,
         1.1510753 ]])

In [195]:
ones=np.ones((X_test.shape[0],1))
X_test=np.hstack((ones,X_test))
X_test

array([[ 1.        ,  0.3994681 , -0.57853753,  0.5125113 ,  1.20874068,
        -0.69292522],
       [ 1.        , -0.31911875, -1.11928535,  0.33162001, -0.23154435,
        -1.94973794],
       [ 1.        , -1.04514761, -0.97530065, -1.31692512, -0.20763182,
        -0.97777923],
       ...,
       [ 1.        ,  0.92238831, -0.43960431, -0.96541692, -0.37486366,
         0.57671761],
       [ 1.        , -2.2109132 ,  0.11947803, -2.35885516, -0.63971321,
        -0.69551665],
       [ 1.        , -1.12429204, -0.86352375, -0.24806717,  0.27690619,
         0.73691105]])

# Gradient Descent

In [274]:
# X : Matrix of m*n
# x : vector : containing single example with n feautures

def hypo(X,theta):
    return np.dot(X,theta)


def predict(X,theta):
    yp=hypo(X,theta) 
    return yp


def score(Y,Yp):
    n=np.sum((Y-Yp)**2)
    d=np.sum((Y-Y.mean())**2)
    return (1-(n/d))*100
    
    

def error(X,y,theta): #cost
    yp=hypo(X,theta)
    e=np.sum((y-yp)**2)
    return e/X.shape[0]



def gradient(X,y,theta):
    M,N=X.shape
    grad=np.zeros((N,))
    
    yp=hypo(X,theta)
    grad=np.dot(yp-y,X)
        
    return grad/M


def gradient_descent(X,y,lr=0.08,iterations=600):
    M,N=X.shape
    theta=np.zeros((N,))
    error_list=[]
    
    for i in range(iterations):
        e=error(X,y,theta)
        error_list.append(e)
        
        #Batch Gradient=> compute grad over an entire data set
        grad=gradient(X,y,theta)
        
        theta=theta-lr*grad
            
    return theta,error_list

In [275]:
theta,error_list=gradient_descent(X_train,Y_train)
theta

array([ 0.86658735, 29.56617554, 94.57615049,  8.57768971, 45.64422732,
        2.45821745])

In [276]:
Y_test.shape

(400,)

In [277]:
Y_pred=predict(X_test_new,theta)

print(Y_pred.shape)

score(Y_test,Y_pred)

(400,)


96.20041663267115

# Adding One Extra Col

In [200]:
ones=np.ones((X_new.shape[0],1))
X_new=np.hstack((ones,X_new))
X_new.shape

(1600, 6)

In [201]:
test_data=pd.read_csv("Test.csv")
test_data

feature_1  feature_2  feature_3  feature_4  feature_5
0     1.015254   2.076209  -0.266435  -2.418088  -0.980503
1    -0.375021   0.953185   0.626719   0.704406  -0.355489
2    -1.024452   0.962991  -0.407942  -1.861274   0.455201
3    -2.489841   0.544802   0.601219  -0.607021  -1.314286
4    -0.384675  -0.833624   1.358552  -0.547932   0.411925
..         ...        ...        ...        ...        ...
395  -0.436959  -0.575844  -1.620908  -0.222588   1.086013
396  -0.421324  -2.417543   0.876275   0.844565   0.171646
397   0.554728   1.768243  -0.897787  -1.193661   0.340563
398  -1.627172   0.856471  -0.000566   0.629387   0.453382
399   0.139310   0.531597  -0.853107   0.031692   1.714893

[400 rows x 5 columns]

In [202]:
X_test_data=test_data.values
X_test_data

array([[ 1.01525387e+00,  2.07620944e+00, -2.66434820e-01,
        -2.41808820e+00, -9.80502790e-01],
       [-3.75021204e-01,  9.53184528e-01,  6.26719138e-01,
         7.04405750e-01, -3.55489211e-01],
       [-1.02445225e+00,  9.62991107e-01, -4.07942004e-01,
        -1.86127383e+00,  4.55201351e-01],
       ...,
       [ 5.54727647e-01,  1.76824345e+00, -8.97787210e-01,
        -1.19366107e+00,  3.40563374e-01],
       [-1.62717246e+00,  8.56470994e-01, -5.65729519e-04,
         6.29386649e-01,  4.53382144e-01],
       [ 1.39310499e-01,  5.31597186e-01, -8.53107053e-01,
         3.16920076e-02,  1.71489304e+00]])

In [203]:
ones=np.ones((X_test_data.shape[0],1))
X_test_data_new=np.hstack((ones,X_test_data))
X_test_data_new.shape

(400, 6)

In [204]:
theta,error_list=gradient_descent(X_new,Y)
theta

array([ 0.31883538, 29.59359198, 94.65067706,  8.37544469, 45.52303635,
        2.46461552])

In [219]:
Y_pred=predict(X_test_data_new,theta)

In [220]:
Y_pred.shape

(400,)

In [239]:
ones=np.ones((Y_pred.shape[0],1))
print(ones.shape)
res=np.hstack((ones,Y_pred.reshape(-1,1)))


for i in range(res.shape[0]):
    res[i,0]=i
    

(400, 1)


In [243]:
df=pd.DataFrame(res,index=None,columns=["Id","target"])
convert_dict = {'Id': int, 
                'target': float 
  
df = df.astype(convert_dict) 
df

Id      target
0      0  112.151684
1      1  115.879768
2      2  -25.876262
3      3  -47.635840
4      4 -102.517982
..   ...         ...
395  395  -88.148510
396  396 -194.762401
397  397  123.081573
398  398   62.994783
399  399   53.281684

[400 rows x 2 columns]

In [245]:
df.to_csv("ans.csv",index=None)